console.log("Loading Script")
const game = new Tetris()
const piece1 = new ForwardL()
const piece2 = new BackwardL()
const p3 = new Cube()
const p4 = new ForwardS()
const p5 = new BackwardS()
const p6 = new Cross()
const p7 = new Line()

game.placePiece(piece1)
game.printMatrix()
